title: Carakan.js
description: A small JavaScript library for converting/transliterating Latin script into Javanese script, also known as Aksara Jawa or Carakan.
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
