title: Carakan.js · Latin <-> Javanese transliterator library
description: A small JavaScript library for converting/transliterating Latin script into Javanese script, also known as Aksara Jawa or Carakan.
show_downloads: true
theme: jekyll-theme-minimal
